1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?


In [5]:
# 1
import numpy as np

def add_matrices(A, B):
    return np.add(A, B)

# Test the function
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
print(add_matrices(A, B))

[[ 8 10 12]
 [14 16 18]]


In [6]:
# 2
import numpy as np

def multiply_matrices(A, B):
    return np.dot(A, B)

# Test the function
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
print(multiply_matrices(A, B))

[[ 58  64]
 [139 154]]


In [7]:
# 3
import numpy as np

def transpose_matrix(A):
    return np.transpose(A)

# Test the function
A = np.array([[1, 2, 3], [4, 5, 6]])
print(transpose_matrix(A))


[[1 4]
 [2 5]
 [3 6]]


In [8]:
# 4
def sort_words(s):
    words = s.split()
    words.sort()
    return ' '.join(words)

# Test the function
s = "Write a Python Program to Sort Words in Alphabetic Order"
print(sort_words(s))


Alphabetic Order Program Python Sort Words Write a in to


In [9]:
# 5
def remove_punctuation(s):
    punctuation = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    return ''.join(c for c in s if c not in punctuation)

# Test the function
s = "Hello, World!!!"
print(remove_punctuation(s))


Hello World
